services:
  robot_bombero_ros:
    build: .
    image: robot_bombero_ros
    network_mode: host
    privileged: true
    devices:
      - /dev/serial0:/dev/serial0
      - /dev/ttyAMA0:/dev/ttyAMA0
      - /dev/video0:/dev/video0
    volumes:
      - ./ros2_ws:/root/ros2_ws
      - ./prorob:/root/prorob
    stdin_open: true
    tty: true
    command: bash
